Update action.yml to speed up removing (refer: https://github.com/jlumbroso/free-disk-space/pull/26/files)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -54,6 +54,18 @@ runs:
         # ======
         # MACROS
         # ======
+        
+        fast_rmdir() {
+          if [[ -d "$1" ]] && [[ -n "$1" ]] && [[ ! "$1" = "/" ]] && [[ ! "$1" = "~" ]]; then
+            echo "Removing directory: $1"
+            sudo find "$1" -type f -delete -print | wc -l
+            sudo rm -rf "$1"
+          fi
+        }
+
+        list_installed_dpkg() {
+          dpkg --get-selections $@ | grep -v deinstall | awk '{print $1}'
+        }
 
         # macro to print a line of equals
         # (silly but works)
@@ -95,20 +107,20 @@ runs:
           echo ""
         }
 
-        # macro to print output of df with caption
-        printDF() {
+        # macro to print output of dh with caption
+        printDH() {
           caption=${1:-}
 
           printSeparationLine '=' 80
           echo "${caption}"
           echo ""
-          echo "$ df -h /"
+          echo "$ dh -h /"
           echo ""
           df -h /
-          echo "$ df -a /"
+          echo "$ dh -a /"
           echo ""
           df -a /
-          echo "$ df -a"
+          echo "$ dh -a"
           echo ""
           df -a
           printSeparationLine '=' 80
@@ -125,7 +137,7 @@ runs:
         AVAILABLE_INITIAL=$(getAvailableSpace)
         AVAILABLE_ROOT_INITIAL=$(getAvailableSpace '/')
 
-        printDF "BEFORE CLEAN-UP:"
+        printDH "BEFORE CLEAN-UP:"
         echo ""
 
 
@@ -134,7 +146,7 @@ runs:
         if [[ ${{ inputs.android }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
           
-          sudo rm -rf /usr/local/lib/android || true
+          fast_rmdir /usr/local/lib/android || true
 
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -147,7 +159,7 @@ runs:
           BEFORE=$(getAvailableSpace)
 
           # https://github.community/t/bigger-github-hosted-runners-disk-space/17267/11
-          sudo rm -rf /usr/share/dotnet || true
+          fast_rmdir /usr/share/dotnet || true
           
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -159,8 +171,8 @@ runs:
         if [[ ${{ inputs.haskell }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
 
-          sudo rm -rf /opt/ghc || true
-          sudo rm -rf /usr/local/.ghcup || true
+          fast_rmdir /opt/ghc || true
+          fast_rmdir /usr/local/.ghcup || true
           
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -172,17 +184,23 @@ runs:
 
         if [[ ${{ inputs.large-packages }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
-          
-          sudo apt-get remove -y '^aspnetcore-.*' || echo "::warning::The command [sudo apt-get remove -y '^aspnetcore-.*'] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^dotnet-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^dotnet-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^llvm-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^llvm-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y 'php.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y 'php.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^mongodb-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mongodb-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y '^mysql-.*' --fix-missing || echo "::warning::The command [sudo apt-get remove -y '^mysql-.*' --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing || echo "::warning::The command [sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y google-cloud-sdk --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-sdk --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get remove -y google-cloud-cli --fix-missing || echo "::debug::The command [sudo apt-get remove -y google-cloud-cli --fix-missing] failed to complete successfully. Proceeding..."
-          sudo apt-get autoremove -y || echo "::warning::The command [sudo apt-get autoremove -y] failed to complete successfully. Proceeding..."
+
+          pkgs=$(list_installed_dpkg 'aspnetcore-*' 'dotnet-*' 'llvm-*' '*php*' 'mongodb-*' 'mysql-*' azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri 'google-cloud-*' 'gcloud-*' || true)
+
+          gcloud_prerm='#!/bin/sh
+          echo $0
+          if [ -d "/usr/lib/google-cloud-sdk" ]; then
+            echo "Cleaning Google Cloud CLI files..."
+            find /usr/lib/google-cloud-sdk -type f -delete -print | wc -l
+            rm -rf /usr/lib/google-cloud-sdk
+            echo "Cleaning Google Cloud CLI manuals..."
+            find /usr/share/man -type f -name "gcloud*" -delete -print | wc -l
+          fi'
+
+          echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli-anthoscli.prerm >/dev/null
+          echo "$gcloud_prerm" | sudo tee /var/lib/dpkg/info/google-cloud-cli.prerm >/dev/null
+
+          sudo apt-get remove --autoremove -y $pkgs || echo "::warning::The command [sudo apt-get remove -y] failed to complete successfully. Proceeding..."
           sudo apt-get clean || echo "::warning::The command [sudo apt-get clean] failed to complete successfully. Proceeding..."
 
           AFTER=$(getAvailableSpace)
@@ -208,7 +226,7 @@ runs:
         if [[ ${{ inputs.tool-cache }} == 'true' ]]; then
           BEFORE=$(getAvailableSpace)
 
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
+          fast_rmdir "$AGENT_TOOLSDIRECTORY" || true
           
           AFTER=$(getAvailableSpace)
           SAVED=$((AFTER-BEFORE))
@@ -237,7 +255,7 @@ runs:
         AVAILABLE_ROOT_END=$(getAvailableSpace '/')
 
         echo ""
-        printDF "AFTER CLEAN-UP:"
+        printDH "AFTER CLEAN-UP:"
 
         echo ""
         echo ""
